name: remove me
on:
  workflow_dispatch:


jobs:
  send_repository_dispatch: 
    runs-on: ubuntu-latest     
    env:
      GH_TOKEN: ${{ secrets.AUTOMATED_USER_TOKEN }}     
    steps:

        - name: Checkout code
          uses: actions/checkout@v3      
          with: 
           repository: oat-sa/test-public1-repo

        - name: get commit and PR number 
          id: fetch_details
          run : | 
            echo ${{ github.repository }}
            git fetch origin develop
            git checkout develop
            echo "last_commit=$(git log -1  | grep commit | awk '{print $2}')" >> $GITHUB_OUTPUT
            echo $last_commit


        - name: Get Latest Pull Request Number
          id: get_pr_num
          run: |
              # Get the number of the latest open pull request
              LATEST_PR_NUMBER=$(gh pr list --json 'number' --state open --base develop | jq -r '.[0].number')
    
              # Print the latest pull request number
              echo "$LATEST_PR_NUMBER" >> $GITHUB_OUTPUT

        - name: print pr num
          run: | 
            echo "${{ steps.get_pr_num.outputs.LATEST_PR_NUMBER}}"
                   

        # - name: send repository dispatch 
        #   uses: peter-evans/repository-dispatch@v2 #this is not reflected
        #   with:
        #       token: '${{ secrets.NEW_TOKEN }}'
        #       repository: oat-sa/test-private-repo
        #       event-type: pull-changes-from-community
        #       client-payload: '{"pr_num": "337", "commit_sha": "${{ steps.fetch_details.outputs.last_commit }}" }'  